"""initial schema

Creates the full Matchly schema: identity, venue graph, matches, video and
processing state, and AI output. See ARCHITECTURE.md section 5.

Revision ID: 0001
Revises:
Create Date: 2026-08-22 15:15:38.834867+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from matchly_shared.domain.columns import GUID

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "otp_challenges",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "otp_challenges_phone_idx", "otp_challenges", ["phone", "created_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("avatar", sa.Text(), nullable=True),
        sa.Column(
            "role", sa.Enum("PLAYER", "VENUE_OPERATOR", "ADMIN", name="user_role"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "users_phone_key",
        "users",
        ["phone"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "venues",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("video_retention_days", sa.Integer(), nullable=False),
        sa.Column("recording_disclosure", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fields",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("venue_id", GUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue_id", "name", name="fields_venue_name_unique"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "venue_members",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("venue_id", GUID(), nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("role", sa.Enum("OPERATOR", "MANAGER", name="venue_role"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["venue_id"], ["venues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue_id", "user_id", name="venue_members_unique"),
    )
    op.create_table(
        "cameras",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("field_id", GUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ONLINE", "OFFLINE", "RECORDING", "ERROR", name="camera_status"),
            nullable=False,
        ),
        sa.Column("stream_url", sa.Text(), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("field_id"),
    )
    op.create_table(
        "matches",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("field_id", GUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "CHECK_IN",
                "RECORDING",
                "UPLOADING",
                "PROCESSING",
                "READY",
                "FAILED",
                name="match_status",
            ),
            nullable=False,
        ),
        sa.Column("join_code", sa.String(length=12), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("created_by", GUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ends_at > starts_at", name="matches_time_order"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("join_code"),
    )
    op.create_index("matches_field_starts_idx", "matches", ["field_id", "starts_at"], unique=False)
    op.create_index("matches_status_idx", "matches", ["status", "starts_at"], unique=False)
    op.create_table(
        "match_players",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("match_id", GUID(), nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("team", sa.Enum("A", "B", name="team"), nullable=False),
        sa.Column("jersey_number", sa.Integer(), nullable=False),
        sa.Column("jersey_override", sa.Boolean(), nullable=False),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jersey_number >= 0 AND jersey_number <= 99", name="match_players_jersey_range"
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id", "user_id", name="match_players_user_unique"),
    )
    op.create_index(
        "match_players_jersey_key",
        "match_players",
        ["match_id", "team", "jersey_number"],
        unique=True,
        postgresql_where=sa.text("jersey_override IS false"),
        sqlite_where=sa.text("jersey_override IS false"),
    )
    op.create_table(
        "videos",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("match_id", GUID(), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=True),
        sa.Column("processed_url", sa.Text(), nullable=True),
        sa.Column("proxy_url", sa.Text(), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "UPLOADING",
                "UPLOADED",
                "PROCESSING",
                "READY",
                "FAILED",
                name="video_status",
            ),
            nullable=False,
        ),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("fps", sa.Float(), nullable=True),
        sa.Column("has_audio", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.TEXT()), "postgresql"),
            nullable=False,
        ),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("purge_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id"),
    )
    op.create_table(
        "highlights",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("match_id", GUID(), nullable=False),
        sa.Column("video_id", GUID(), nullable=True),
        sa.Column("player_id", GUID(), nullable=True),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "GOAL_AREA_ACTION",
                "HIGH_INTENSITY",
                "CELEBRATION",
                "TEAM_BUILDUP",
                "GENERIC",
                name="highlight_type",
            ),
            nullable=False,
        ),
        sa.Column("video_url", sa.Text(), nullable=True),
        sa.Column("video_url_vertical", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column(
            "signals",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.TEXT()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_time > start_time", name="highlights_time_order"),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_id"], ["match_players.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("highlights_match_score_idx", "highlights", ["match_id", "score"], unique=False)
    op.create_index(
        "highlights_player_idx", "highlights", ["player_id", "created_at"], unique=False
    )
    op.create_table(
        "player_tracks",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("video_id", GUID(), nullable=False),
        sa.Column("track_ref", sa.String(length=64), nullable=False),
        sa.Column("jersey_number", sa.Integer(), nullable=True),
        sa.Column("jersey_confidence", sa.Float(), nullable=True),
        sa.Column("player_id", GUID(), nullable=True),
        sa.Column("first_seen", sa.Float(), nullable=False),
        sa.Column("last_seen", sa.Float(), nullable=False),
        sa.Column(
            "samples",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.TEXT()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["player_id"], ["match_players.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id", "track_ref", name="player_tracks_ref_unique"),
    )
    op.create_table(
        "processing_jobs",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("video_id", GUID(), nullable=False),
        sa.Column(
            "step",
            sa.Enum(
                "VALIDATE",
                "PROBE",
                "TRANSCODE",
                "SAMPLE_FRAMES",
                "DETECT_PLAYERS",
                "TRACK",
                "JERSEY_OCR",
                "SCORE_EVENTS",
                "CUT_CLIPS",
                "THUMBNAILS",
                "PERSIST",
                name="job_step",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "SUCCEEDED", "FAILED", "SKIPPED", name="job_status"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.TEXT()), "postgresql"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id", "step", name="processing_jobs_step_unique"),
    )
    op.create_index(
        "processing_jobs_status_idx", "processing_jobs", ["status", "updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("processing_jobs_status_idx", table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_table("player_tracks")
    op.drop_index("highlights_player_idx", table_name="highlights")
    op.drop_index("highlights_match_score_idx", table_name="highlights")
    op.drop_table("highlights")
    op.drop_table("videos")
    op.drop_index(
        "match_players_jersey_key",
        table_name="match_players",
        postgresql_where=sa.text("jersey_override IS false"),
        sqlite_where=sa.text("jersey_override IS false"),
    )
    op.drop_table("match_players")
    op.drop_index("matches_status_idx", table_name="matches")
    op.drop_index("matches_field_starts_idx", table_name="matches")
    op.drop_table("matches")
    op.drop_table("cameras")
    op.drop_table("venue_members")
    op.drop_table("refresh_tokens")
    op.drop_table("fields")
    op.drop_table("venues")
    op.drop_index(
        "users_phone_key",
        table_name="users",
        postgresql_where=sa.text("deleted_at IS NULL"),
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("users")
    op.drop_index("otp_challenges_phone_idx", table_name="otp_challenges")
    op.drop_table("otp_challenges")
    # Native enum types are created implicitly by the sa.Enum columns above but are
    # never dropped by autogenerate, which breaks a downgrade/upgrade cycle.
    for enum_name in (
        "highlight_type",
        "job_status",
        "job_step",
        "video_status",
        "team",
        "match_status",
        "camera_status",
        "venue_role",
        "user_role",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
    # ### end Alembic commands ###
